Algoritmo "Exercicio 3"
// Disciplina   : Lógica de programação com Portugol
// Professor   : Cleberson
// Descrição   :
// Autor(a)    : Gabriel Oliveira
// Data atual  : 14/11/2022
Var
// Seção de Declarações das variáveis 
km,autonomia,gasto:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
km <- 2000
autonomia <- 10
gasto <- km*autonomia
escreval("Serão gastos:",gasto," litros de gasolina.")
Fimalgoritmo